baby:
  opus:
    path : d:/usr/jornahlee/opus-front
file:
  rootPath: d:/usr/jornahlee/opus-front
  pathLevel: 2
server:
  port : 1011
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB
