baby:
  opus:
    path : /usr/jornahlee/opus-front
server:
  port : 1011
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB
